name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0
  shared_preferences: ^2.0.16
  # shared_preferences: ^2.0.15

  cupertino_icons: ^0.1.2
  #TODO: Step 1 - Add the rFlutter Alert package as a dependency here and use "Packages get".

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

